[package]
name = "mongo-rabbitmq-connector"
version = "0.1.0"
edition = "2021"

[dependencies]
mongodb = { version = "3" }
lapin = { version = "2.5"}
futures-util = "0.3"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
dotenv = "0.15"
config = "0.13"
log = "0.4"
env_logger = "0.11"
