[workspace]
resolver = "2"
members = ["mongodb_rabbitmq_connector", "mongodb_rabbitmq_connectord"]

[workspace.dependencies]
mongodb = { version = "3" }
lapin = { version = "2.5" }
futures-util = "0.3"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
dotenv = "0.15"
config = "0.13"
env_logger = "0.11"
tracing = "0.1"
bson = { version = "2" }
thiserror = "1"
async-trait = "0.1"
tracing-subscriber = "0.3"
clap = { version = "4.5", features = ["derive"] }
