version: '3.8'
services:
  mongodb:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  connector:
    build:
      context: .
      dockerfile: ./mongodb_rabbitmq_connectord/Dockerfile
    container_name: connector
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      MONGO_URI: "mongodb://root:example@mongodb:27017/"
      RABBITMQ_URI: "amqp://guest:guest@rabbitmq:5672/"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    # Uncomment for debugging
    # ports:
    #   - "8080:8080" # health check
    #   - "3000:3000" # your app port if needed

volumes:
  mongo_data:
  rabbitmq_data:
