[package]
name = "mrcon-mongodb"
version = "0.1.0"
description = "MongoDB functionality for mrcon MongoDB to RabbitMQ connector"

authors.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
mrcon-core = { path = "../core" }
mrcon-config = { path = "../config" }
mongodb.workspace = true
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
thiserror.workspace = true
