[package]
name = "mrcon-core"
version = "0.1.0"
description = "Core types and traits for mrcon MongoDB to RabbitMQ connector"

authors.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
mongodb.workspace = true
lapin.workspace = true
serde_json.workspace = true
thiserror.workspace = true
