name: "Test Suite"
on:
  push:
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Ensure rustfmt is installed and setup problem matcher
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: |
            make check check-format check-clippy build test || docker compose logs
        timeout-minutes: 5